//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.PrimaryPrefCustomers = new HashSet<Customer>();
            this.SecondaryPrefCustomers = new HashSet<Customer>();
            this.Equipment = new HashSet<Equipment>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int ActivityID { get; set; }
        public string Name { get; set; }
        public string imagepath { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Customer> PrimaryPrefCustomers { get; set; }
        public virtual ICollection<Customer> SecondaryPrefCustomers { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
