//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerTypeID = 1;
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int ContactID { get; set; }
        public int CustomerTypeID { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<int> PrimaryDesintationID { get; set; }
        public Nullable<int> SecondaryDestinationID { get; set; }
        public Nullable<int> PrimaryActivityID { get; set; }
        public Nullable<int> SecondaryActivityID { get; set; }
        public string Notes { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Activity PrimaryActivity { get; set; }
        public virtual Activity SecondaryActivity { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Destination PrimaryDestination { get; set; }
        public virtual Destination SecondaryDestination { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
