//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int EquipmentID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
