//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ReservationID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public int ContactID { get; set; }
        public Nullable<int> TripID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
