//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Reservations = new HashSet<Reservation>();
            this.Activities = new HashSet<Activity>();
        }
    
        public int TripID { get; set; }
        public int LocationID { get; set; }
        public int LodgingID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> TripCostUSD { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Lodging Lodging { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
